// <auto-generated />
using System;
using ComplianceDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComplianceDashboard.Data.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    partial class DashboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComplianceDashboard.Entities.AppealAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("answer");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("question_key");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("question_text");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("CaseId", "QuestionKey")
                        .IsUnique();

                    b.ToTable("appeal_answers", (string)null);
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.AppealCase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("case_type");

                    b.Property<string>("ClientMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("client_message");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MissingInfoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_info_json");

                    b.Property<string>("OperationId")
                        .HasColumnType("text")
                        .HasColumnName("operation_id");

                    b.Property<string>("RouteTo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("route_to");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SupportSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("support_summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("RouteTo");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("appeal_cases", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "case_2",
                            CaseType = "ACCOUNT_BLOCK_APPEAL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MissingInfoJson = "[\"Source of funds confirmation is required\", \"Purpose of incoming transfers is required\"]",
                            RouteTo = "COMPLIANCE",
                            Status = "NEED_MORE_INFO",
                            SupportSummary = "Client reported account restriction after several incoming transfers. Supporting documents are not attached yet.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_2"
                        },
                        new
                        {
                            Id = "case_3",
                            CaseType = "OPERATION_CONFIRMATION",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MissingInfoJson = "[]",
                            OperationId = "op_3",
                            RouteTo = "SUPPORT",
                            Status = "SUBMITTED",
                            SupportSummary = "Client confirmed service payment. Recipient is a company/service. Payment check is attached.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_3"
                        });
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.AppealDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("MockUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("mock_url");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("appeal_documents", (string)null);
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.Operation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BlockReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("block_reason_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("RecipientAccount")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("recipient_account");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("operations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "op_1",
                            Amount = 250000m,
                            BlockReasonCode = "CLIENT_CONFIRMATION_REQUIRED",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "KZT",
                            RecipientAccount = "KZ00 **** **** 1234",
                            RecipientName = "Alisher M.",
                            Status = "PENDING_CONFIRMATION",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_1"
                        },
                        new
                        {
                            Id = "op_3",
                            Amount = 45000m,
                            BlockReasonCode = "CLIENT_CONFIRMATION_REQUIRED",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "KZT",
                            RecipientAccount = "KZ00 **** **** 9876",
                            RecipientName = "Service Company",
                            Status = "PENDING_CONFIRMATION",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_3"
                        });
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.SupportDecision", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("decision");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("support_decisions", (string)null);
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("account_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user_1",
                            AccountStatus = "LIMITED",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FullName = "Andrey K.",
                            Phone = "+7 777 000 00 00",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "user_2",
                            AccountStatus = "LIMITED",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FullName = "Client Account Appeal",
                            Phone = "+7 777 000 00 02",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "user_3",
                            AccountStatus = "ACTIVE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FullName = "Client Operation Confirmation",
                            Phone = "+7 777 000 00 03",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.AppealAnswer", b =>
                {
                    b.HasOne("ComplianceDashboard.Entities.AppealCase", "Case")
                        .WithMany("Answers")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.AppealCase", b =>
                {
                    b.HasOne("ComplianceDashboard.Entities.Operation", "Operation")
                        .WithMany("AppealCases")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ComplianceDashboard.Entities.User", "User")
                        .WithMany("AppealCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.AppealDocument", b =>
                {
                    b.HasOne("ComplianceDashboard.Entities.AppealCase", "Case")
                        .WithMany("Documents")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.Operation", b =>
                {
                    b.HasOne("ComplianceDashboard.Entities.User", "User")
                        .WithMany("Operations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.SupportDecision", b =>
                {
                    b.HasOne("ComplianceDashboard.Entities.AppealCase", "Case")
                        .WithMany("Decisions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.AppealCase", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Decisions");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.Operation", b =>
                {
                    b.Navigation("AppealCases");
                });

            modelBuilder.Entity("ComplianceDashboard.Entities.User", b =>
                {
                    b.Navigation("AppealCases");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
